---
- name: Install LAMP
  apt: pkg={{item}} state=installed update_cache=true
  become: yes
  become_method: sudo
  with_items:
    - apache2
    - mysql-server
    - php5
    - libapache2-mod-php5

- name: Install RRDTool
  apt: pkg=rrdtool state=installed
  become: yes
  become_method: sudo

- name: Install SNMP
  apt: pkg={{item}} state=installed
  become: yes
  become_method: sudo
  with_items:
    - snmp
    - snmpd

- name: Install cacti package
  apt: pkg={{item}} state=installed
  become: yes
  become_method: sudo
  with_items:
    - cacti
    - cacti-spine

- name: Start SNMP service
  service: name=snmpd state=started enabled=yes
