---
- name: Create SSH directory
  command: mkdir -p ~/.ssh

- name: Copy public SSH key
  copy: src=id_rsa.pub dest=~/.ssh/authorized_keys

- name: Install common packages
  apt: pkg={{item}} state=installed update_cache=true
  become: yes
  become_method: sudo
  with_items:
    - htop
    - avahi-daemon
