---
- name: Create SSH directory
  file: path=/home/{{ ansible_env.USER }}/.ssh state=directory

- name: Copy public SSH key
  copy: src=id_rsa.pub dest=/home/{{ ansible_env.USER }}/.ssh/authorized_keys

- name: Install common packages
  apt: pkg={{item}} state=installed update_cache=true
  become: yes
  become_method: sudo
  with_items: packages

- name: Add SNMP configuration
  become: yes
  become_method: sudo
  template: src=snmp.conf.j2 dest=/etc/snmp/snmpd.conf
