---
- name: Add SSH key
  authorized_key: user={{ ansible_env.USER }} key="{{ item }}"
  with_file:
    - id_rsa.pub

- name: Generate SSH keypair
  command: creates="/home/{{ ansible_env.USER }}/.ssh/id_rsa" ssh-keygen -t rsa -C {{ ssh_email }} -f /home/{{ ansible_env.USER }}/.ssh/id_rsa -N ""

- name: Install common packages
  apt: pkg={{item}} state=installed update_cache=true
  become: yes
  become_method: sudo
  with_items: packages

- name: Add SNMP configuration
  become: yes
  become_method: sudo
  template: src=snmp.conf.j2 dest=/etc/snmp/snmpd.conf
