---
- name: Add build-essential packages
  become: yes
  become_method: sudo
  apt: pkg=build-essential state=installed

- name: Add RVM key
  command: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  # apt_key: keyserver=hkp://keys.gnupg.net id=409B6B1796C275462A1703113804BB82D39DC0E3

- name: Fetch RVM script
  get_url: url=https://get.rvm.io dest=/tmp/rvm.sh mode=0755

- name: Install RVM
  command: /tmp/rvm.sh --autolibs=read-fail stable

- name: Install Ruby dependencies
  become: yes
  become_method: sudo
  command: /home/{{ ansible_env.USER }}/.rvm/bin/rvm requirements

- name: Install Rubies
  command: /home/{{ ansible_env.USER }}/.rvm/bin/rvm install {{item}}
  with_items: ruby_versions
  
- name: Set default Ruby
  command: /home/{{ ansible_env.USER }}/.rvm/bin/rvm use {{default_ruby}} --default
